name: Fast Validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [dev]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Timeout after 10 minutes

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Quick Build Test
        run: |
          echo "Testing production build..."
          npm run build
          echo "✓ Build successful"

      - name: Validate HTML Structure
        run: |
          if [ -f "index.html" ]; then
            echo "✓ index.html exists"
            # Quick HTML structure check
            if grep -q "<html" index.html && grep -q "</html>" index.html; then
              echo "✓ Valid HTML structure"
            else
              echo "✗ Invalid HTML structure"
              exit 1
            fi
          else
            echo "✗ index.html not found"
            exit 1
          fi

      - name: Validate CSS & Documentation
        run: |
          # Quick CSS check
          if [ -f "src/style.css" ]; then
            echo "✓ CSS file exists"
            # Run CSS linting (fast)
            npm run lint:css
            echo "✓ CSS validation passed"
          else
            echo "✗ src/style.css not found"
            exit 1
          fi

          # Quick documentation check
          if [ -f "README.md" ]; then
            echo "✓ README.md exists"
          else
            echo "✗ README.md not found"
            exit 1
          fi

          echo "✓ All validations passed successfully"
