name: Validate

on:
  pull_request:
    branches: [main]
  push:
    branches: [dev]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          # Basic HTML validation
          if [ -f "index.html" ]; then
            echo "✓ index.html exists"
            # Check for basic HTML structure
            if grep -q "<html" index.html && grep -q "</html>" index.html; then
              echo "✓ Basic HTML structure found"
            else
              echo "✗ Invalid HTML structure"
              exit 1
            fi
          else
            echo "✗ index.html not found"
            exit 1
          fi

      - name: Validate CSS
        run: |
          # Basic CSS validation
          if [ -f "style.css" ]; then
            echo "✓ style.css exists"
          else
            echo "✗ style.css not found"
            exit 1
          fi

      - name: Check README
        run: |
          if [ -f "README.md" ]; then
            echo "✓ README.md exists"
          else
            echo "✗ README.md not found"
            exit 1
          fi
