name: Validate

on:
  pull_request:
    branches: [main]
  push:
    branches: [dev]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          # Basic HTML validation
          if [ -f "index.html" ]; then
            echo "✓ index.html exists"
            # Check for basic HTML structure using more precise patterns
            if grep -q "<html[[:space:]>]" index.html && grep -q "</html[[:space:]>]" index.html; then
              echo "✓ Basic HTML structure found"
            else
              echo "✗ Invalid HTML structure"
              exit 1
            fi
          else
            echo "✗ index.html not found"
            exit 1
          fi

      - name: Setup Node.js for validation
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate CSS
        run: |
          # Check if CSS files exist (now in src/ directory)
          if [ -f "src/style.css" ]; then
            echo "✓ src/style.css exists"
            
            # Run CSS linting using local stylelint
            echo "Running CSS syntax checks..."
            npm run lint:css || {
              echo "✗ CSS syntax errors found"
              exit 1
            }
            echo "✓ CSS syntax validation passed"
            
            # Check for basic CSS structure
            if grep -q "{" src/style.css && grep -q "}" src/style.css; then
              echo "✓ Basic CSS structure found (contains braces)"
            else
              echo "⚠ Warning: No CSS rules found in src/style.css"
            fi
            
            # Check for common CSS properties
            if grep -qE "(color|background|font|margin|padding|width|height)" src/style.css; then
              echo "✓ Common CSS properties detected"
            else
              echo "⚠ Warning: No common CSS properties found"
            fi
            
          else
            echo "✗ src/style.css not found"
            exit 1
          fi

          # The npm run lint:css command already checks all CSS files in src/
          echo "✓ All CSS files validated successfully"

      - name: Check README
        run: |
          if [ -f "README.md" ]; then
            echo "✓ README.md exists"
          else
            echo "✗ README.md not found"
            exit 1
          fi
