name: Fast Validation

on:
  pull_request:
    branches: [main, dev] # Support PRs to both main and dev branches
  push:
    branches: [dev]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Timeout after 10 minutes

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Quick Build Test
        run: |
          echo "Testing production build..."
          npm run build
          echo "✓ Build successful"

      - name: Validate HTML Structure
        run: |
          if [ -f "index.html" ]; then
            echo "✓ index.html exists"
            # Quick HTML structure check
            if grep -q "<html" index.html && grep -q "</html>" index.html; then
              echo "✓ Valid HTML structure"
            else
              echo "✗ Invalid HTML structure"
              exit 1
            fi
          else
            echo "✗ index.html not found"
            exit 1
          fi

      - name: Code Quality & Linting
        run: |
          echo "Running code quality checks..."

          # Check code formatting
          npm run format:check
          echo "✓ Code formatting validation passed"

          # Run all linting (CSS + JavaScript)
          npm run lint
          echo "✓ Linting validation passed"

      - name: Test Suite
        run: |
          echo "Running comprehensive test suite..."

          # Run all tests with coverage
          npm run test:run
          echo "✓ All unit tests passed successfully"

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium firefox

      - name: E2E Test Suite
        run: |
          echo "Running End-to-End test suite..."

          # Set CI environment and run E2E tests
          export CI=true
          npm run test:e2e:ci
          echo "✓ All E2E tests passed successfully"

      - name: Upload E2E Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Validate CSS & Documentation
        run: |
          # Quick CSS check
          if [ -f "src/style.css" ]; then
            echo "✓ CSS file exists"
          else
            echo "✗ src/style.css not found"
            exit 1
          fi

          # Quick documentation check
          if [ -f "README.md" ]; then
            echo "✓ README.md exists"
          else
            echo "✗ README.md not found"
            exit 1
          fi

          echo "✓ All validations passed successfully"
